### ISSUE TITLE
main in package.json should be .js not .jsx

### ISSUE THREAD

**Issue by avraam-mavridis-sociomantic** [sociomantic-tsunami/flounder-react#1]
If a project thas is not using `jsx`  ( and of-course jsx loader ) imports Flounder will get an error, something like

`You may need an appropriate loader to handle this file type.`

The question is, is it a reason that we Flounder is written has `jsx` extension? If yes, then maybe we should have a `postinstall` script in package.json to compile it to `js` and point the main there?

**Comment by mousemke** [comment]
this is a hard one.  i'm open to either way if there is a reason, but my thoughts were that is _is_ jsx, but as well, we dont compile anything due to not wanting to bundle react.  so keeping the file a `.jsx`is a warning that you cant use it otherwise.  @avraam-mavridis-sociomantic thoughts?

**Comment by avraam-mavridis-sociomantic** [comment]
I think is doable to keep `.jsx` and in the same time don't affect the projects that dont use `jsx` without having to bundle React.

In the package.json you can have two scripts

```
    "compile": "babel --presets es2015,stage-0,react --plugins transform-react-jsx -d lib/ src/",
    "prepublish": "npm run compile",
```

prepublish will run before publishing flounder-react to npm, creating a `lib` folder with the `.js` version of the package. Then in main you can have something like:

```
"main": "./lib/index.js",
```

pointing to the entry of the `lib` folder.

And list react as `peerDepedency` to not include it in the compiled version

```
  "peerDependencies": {
    "react": "^15.0.1 || ^0.14.8",
    "react-dom": "^15.0.1 || ^0.14.8"
  },
```

and maybe in `.gitignore` a `lib` entry to not "pollute" the repo with the compiled version (that will mean probably that the package cannot included directly from the repo)

I haven't try this workflow pattern with `transform-react-jsx` included (but I have try [without it here](https://github.com/AvraamMavridis/react-clickoutside-component/blob/master/package.json), hopefully is doable) :smiley:

**Comment by mousemke** [comment]
for sure.  it would be great to be able to compile it without actually _including_ react

**Comment by mousemke** [comment]
@avraam-mavridis-sociomantic any movement on this? i will close it.  afaik, Anyone using react will also be able to compile it.  And anyone not using react can just use non-react flounder

**Comment by avraam-mavridis-sociomantic** [comment]
👍
