### ISSUE TITLE
Ability to pass a full set of custom CSS class names as a prop?

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/flounder-react#10]
I’d like to implement the ability to pass an object of custom CSS class names that override/replace those in `/core/classes.js`. (The use case is to support dynamically-generated class names using CSS Modules).

@mousemke what do you reckon? You see any potential issues with that?

**Comment by mousemke** [comment]
should be no prob, but i'd suggest that this is a deeper fix and should be addressed at a flounder level.  it already has this: [class config options](https://github.com/sociomantic-tsunami/flounder-react#available-config-options), but it's a bit of a holdover from before there was a classes file.  It could be retrofit to to compare and overwrite the classes file [here](https://github.com/sociomantic-tsunami/flounder/blob/master/src/core/flounder.js#L356-L367).  Also probably minor other changes to make it smooth, but it doesnt sound that painful

**Comment by mousemke** [comment]
can you do this on `flounder1.0.0`? PR into master isnt the best strategy

**Comment by leandro-lucarella-sociomantic** [comment]
Closing as this project is going to be archived.
