### ISSUE TITLE
onFocus / onBlur callback props

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/flounder-react#11]
Would be useful to have `onFocus` and `onBlur` callbacks as props. OK for me go ahead and implement that @mousemke? Any potential issues?

**Comment by mousemke** [comment]
yes and no. things are weird right now and i feel i dont have time to give flounder-react enough love, _however_, bear in mind flounder `1.0.0`. (though this sounds like it's an issue on react side)  sounds good, but be mindful of things.

`flounder-react` will have to be caught up a bit after the 1.0.0 release

**Comment by conor-cafferkey-sociomantic** [comment]
OK, it’s not super-urgent so I’ll wait till after 1.0.0

**Comment by leandro-lucarella-sociomantic** [comment]
Closing as this project is going to be archived.
