### ISSUE TITLE
ANNOUNCEMENT THREAD: flounder-react - the journey to 1.0.0

### ISSUE THREAD

**Issue by mousemke** [sociomantic-tsunami/flounder-react#12]
In the next days, flounder-react will get overhauled to use and mirror the structure of flounder 1.0.0.  at that time, issues here will finally be dealt with (some of them may be moved to the flounder repo if it's an issue that affects all builds, some may be closed if the issue is already taken care of).  

Once it supports 1.0.0, we will accept PRs based off of the 1.0.0 code (it just would have been too much to support fixes and apply them to the 0.8.5 and 1.0.0 code bases)

Thanks for your patience all.

-mouse

( mentioned due to long neglected issues you've opened:
@jolene-borrelli-sociomantic @conor-cafferkey-sociomantic @damian-rodriguez-sociomantic @avraam-mavridis-sociomantic )

**Comment by leandro-lucarella-sociomantic** [comment]
Closing as this project is going to be archived.
