### ISSUE TITLE
Use spread instead of slice

### ISSUE THREAD

**Issue by avraam-mavridis-sociomantic** [sociomantic-tsunami/flounder-react#4]
I think it will make it a bit more clear to convert the lines like

`Array.prototype.slice.call( anArray, 0 )` 

to

 `[ ...anArray ]`

**Comment by mousemke** [comment]
this totally borked flounder in ie11.  rolling back

**Comment by avraam-mavridis-sociomantic** [comment]
This proposition was for `src` that would be compiled to es5 before published, related to https://github.com/sociomantic-tsunami/flounder-react/issues/1

Otherwise even the `class` breaks in every IE.

**Comment by avraam-mavridis-sociomantic** [comment]
The reason of the break is the missing plugin https://babeljs.io/docs/plugins/transform-object-rest-spread/ in the babelify config on the gulp file.
