### ISSUE TITLE
No compilation method

### ISSUE THREAD

**Issue by josh-wilson-sociomantic** [sociomantic-tsunami/flounder-react#6]
Since the last release, where `core` was removed, we're not actually compiling the jsx file for `dist`. 

Wanted:

Compile flounder-react with flounder dependencies for a complete react-component.

**Comment by josh-wilson-sociomantic** [comment]
I started with a local fork for this, but getting very odd errors. So nothing for a PR yet.

basically adapting flounder-core:

```
function browserifyFiles( folder, filename, ext )
{
    ext = ext || '.js';

    browserify( folder + '/' + filename + ext )
        .transform( babelify,{ presets: [ 'es2015', 'stage-0', 'react' ] } )
        .bundle()
        .pipe( fs.createWriteStream( __dirname + '/dist/' + filename + ext ) )
        .on( 'finish', function( err )
        {
          console.log( 'err' , err  );
            gulp.src( './dist/' + filename + ext )
                .pipe( header( licenceLong ) )
                .pipe( gulp.dest( './dist/' ) )
        } );
};

gulp.task( 'compile', [], function()
{
        browserifyFiles( 'src', 'flounder.react', '.jsx' );

} )
```

I'll PR as soon as i've debugged my local.

**Comment by mousemke** [comment]
this _was_ intentional, but i'm open to other solutions.  we userd to compile it, but it included react, so the file size was huge

**Comment by josh-wilson-sociomantic** [comment]
aha. Riggghhhttt. I remember that now :) Makes sense aaayyye.

Okay well the current setup is looking for `core` files that dont exist in our dist folder. So perhaps the solution there is just a wee copy of those across.

**Comment by mousemke** [comment]
something like this? https://github.com/sociomantic-tsunami/flounder-react/blob/master/package.json#L13

**Comment by josh-wilson-sociomantic** [comment]
heh, indeed. It's not working if you npm the latest release though.

You only get `flounder.react.jsx`

**Comment by mousemke** [comment]
there were release issues.  flounder `0.8.0` also became `0.8.1` ^^

**Comment by mousemke** [comment]
@josh-wilson-sociomantic can this be closed?   anything else we need out of it?

check out 0.1.1 i think it's a good release

**Comment by josh-wilson-sociomantic** [comment]
Closing, as you note, it shouldn't be compiled for dist.
