### ISSUE TITLE
defaults.js exporting/importing errors

### ISSUE THREAD

**Issue by damian-rodriguez-sociomantic** [sociomantic-tsunami/flounder-react#7]
when importing flounder react to our components we get different errors as result of an unsuccessful import/export for `defaults.js` although the way to import is the proper way in react. 

[this line](https://github.com/sociomantic-tsunami/flounder-react/blob/master/src/flounder.react.jsx#L9)
`import { setDefaultOption } from './core/defaults';`

and [this line](https://github.com/sociomantic-tsunami/flounder-react/blob/master/src/core/flounder.js#L5)
`import { defaultOptions }   from './defaults';`

this seems to work
`import defaults  from './core/defaults';`
`const setDefaultOption = defaults.setDefaultOption;`

`import defaults  from './defaults';`
`const defaultOptions = defaults.defaultOptions;`

@mousemke

**Comment by mousemke** [comment]
feel free to PR if you need it.  I wont have time to jump on this til next week

**Comment by damian-rodriguez-sociomantic** [comment]
ok, will do it; thanks @mousemke

**Comment by mousemke** [comment]
ok, this one i have. babel changed and this is no longer valid destructring

**Comment by leandro-lucarella-sociomantic** [comment]
Closing as this project is going to be archived.
