### ISSUE TITLE
first select option is overwritten by placeholder after changing props

### ISSUE THREAD

**Issue by damian-rodriguez-sociomantic** [sociomantic-tsunami/flounder-react#8]
when flounder component renders for the first time all is fine, but after changing props and the flounder component renders again ( if we have placeholder set ) the first select option gets overwritten by the placeholder. This is happening [here](https://github.com/sociomantic-tsunami/flounder-react/blob/master/src/core/defaults.js#L112)

@mousemke is there any specific reason to overwrite the first option with the placeholder  `data[ 0 ] = _default`  instead of adding the placeholder as new item to the beginning of the data array `data.unshift( _default )`

**Comment by leandro-lucarella-sociomantic** [comment]
Closing as this project is going to be archived.
