### ISSUE TITLE
Error when trying to defineProperty

### ISSUE THREAD

**Issue by jolene-borrelli-sociomantic** [sociomantic-tsunami/flounder-react#9]
When trying to render a Flounder React component, the following error appears

`makeAssimilatePrototype.js:21 Uncaught TypeError: Cannot set property version of #<FlounderReact> which has only a getter`

I am using Chrome, Version 51.0.2704.103 (64-bit). When I comment out the following [code](https://github.com/sociomantic-tsunami/flounder-react/blob/master/src/flounder.react.jsx#L262). Everything is just groovy. 

It happens when the component is rendered directly and when it is wrapped in a parent component.

**Comment by leandro-lucarella-sociomantic** [comment]
Closing as this project is going to be archived.
